### ISSUE TITLE
prayers.json not created

### ISSUE THREAD

**Issue by AbdelrahmanElhosiny** [0xzer0x/statusbar-prayers#1]
The module in polybar is displaying 

> jq: error: Could not open file /home/abdelrahman/.local/share/prayer.json: No such file or directory

so I tried running prayer-times.sh and it gave me this error

> ./prayer-times.sh: 17: [[: not found
> ./prayer-times.sh: 23: [[: not found
> ./prayer-times.sh: 23: !=: not found
> Creating at jobs for prayer notification...
> /home/abdelrahman/.local/bin/add-prayers-at-jobs.sh: 7: [[: not found
> jq: error: Could not open file /home/abdelrahman/.local/share/prayers.json: No such file or directory
> jq: error: Could not open file /home/abdelrahman/.local/share/prayers.json: No such file or directory
> jq: error: Could not open file /home/abdelrahman/.local/share/prayers.json: No such file or directory
> jq: error: Could not open file /home/abdelrahman/.local/share/prayers.json: No such file or directory
> jq: error: Could not open file /home/abdelrahman/.local/share/prayers.json: No such file or directory
> at: refusing to create job destined in the past
> at: refusing to create job destined in the past
> at: refusing to create job destined in the past
> at: refusing to create job destined in the past
> at: refusing to create job destined in the past

**Comment by 0xzer0x** [comment]
> ./prayer-times.sh: 17: [[: not found

This seems to be due to running the script using a shell other than sh/bash, does running `sh prayer-times.sh` or `bash prayer-times.sh` give the same error ?

**Comment by AbdelrahmanElhosiny** [comment]
> > ./prayer-times.sh: 17: [[: not found
> 
> This seems to be due to running the script using a shell other than sh/bash, does running `sh prayer-times.sh` or `bash prayer-times.sh` give the same error?

Yes, I did run it using bash and zsh, started with zsh at the beginning and switched to bash and still had the same issue, alos I tried running it on both i3wm and gnome with the same error message

**Comment by AbdelrahmanElhosiny** [comment]
when I run add-prayer-at-jobs.sh with bash it gives me this 

> add-prayers-at-jobs.sh: 7: [[: not found
> warning: commands will be executed using /bin/sh
> job 47 at Mon Nov  6 04:44:00 2023
> warning: commands will be executed using /bin/sh
> job 48 at Mon Nov  6 11:38:00 2023
> warning: commands will be executed using /bin/sh
> job 49 at Mon Nov  6 14:44:00 2023
> warning: commands will be executed using /bin/sh
> job 50 at Mon Nov  6 17:04:00 2023
> warning: commands will be executed using /bin/sh
> job 51 at Mon Nov  6 18:24:00 2023

and the module in polybar display the following

> /home/abdelrahman/.local/bin/prayer.sh:  53: arithmetic expression: expected primary  : "1699238640" - "1699229724"

**Comment by AbdelrahmanElhosiny** [comment]
Thank you very much for answering, now when i run prayer.sh with bash it runs fine but in polybar it is giving me an error that it gives when it runs with sh.

edit: I edited the header in prayer.sh to be #!/bin/bash and that made it work,  gazak allah kol kher
